package org.is70002024.market.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InsyteLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsyteLogAllPropertiesEquals(InsyteLog expected, InsyteLog actual) {
        assertInsyteLogAutoGeneratedPropertiesEquals(expected, actual);
        assertInsyteLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsyteLogAllUpdatablePropertiesEquals(InsyteLog expected, InsyteLog actual) {
        assertInsyteLogUpdatableFieldsEquals(expected, actual);
        assertInsyteLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsyteLogAutoGeneratedPropertiesEquals(InsyteLog expected, InsyteLog actual) {
        assertThat(expected)
            .as("Verify InsyteLog auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsyteLogUpdatableFieldsEquals(InsyteLog expected, InsyteLog actual) {
        assertThat(expected)
            .as("Verify InsyteLog relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getActivity()).as("check activity").isEqualTo(actual.getActivity()))
            .satisfies(e -> assertThat(e.getRundate()).as("check rundate").isEqualTo(actual.getRundate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsyteLogUpdatableRelationshipsEquals(InsyteLog expected, InsyteLog actual) {
        // empty method
    }
}
